name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >-
            scheme-basic
            beamer
            biblatex
            enumitem
            fileinfo
            hypdoc
            hyperref
            l3build
            listings
            metalogo
            parskip
            pgf
            pgfopts
            setspace
            xurl
      - name: document
        run: l3build doc
      - name: build
        run: l3build ctan -q -H --show-log-on-error
  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
      pull-requests: write
    needs:
      - build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
